repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: issue-number-from-branch
        name: 브랜치 이슈번호 커밋 제목에 자동 추가
        entry: scripts/hooks/prepare-commit-msg
        language: script
        stages: [prepare-commit-msg]
